### ISSUE TITLE
Crash on attempt to craft a Copper Jetpack from Iron Jetpacks

### ISSUE THREAD

**Issue by uhloin** [CyclopsMC/IntegratedCrafting#117]
#### Issue type:

- :bug: Bug 

____

#### Short description:

In 1.21.1 with Iron Jetpacks mod I tried to craft a Copper Jetpack, clicked Ctrl+[+] to auto-craft sub-elements and got this crash

____

#### Versions:

- This mod: 1.1.11
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.68

#### Log file:

[crash-2024-11-10_16.37.12-server.txt](https://github.com/user-attachments/files/17691415/crash-2024-11-10_16.37.12-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by uhloin** [comment]
After install new versions Storage Terminal doesn't see items in colossal chest and fluids in tanks. Even rollback of IntegratedTerminals, IntegratedCrafting and CommonCapabilities didn't help

**Comment by rubensworks** [comment]
Best to create a separate bug report if you can consistently reproduce it, as this seems unrelated to the issue reported above.

**Comment by uhloin** [comment]
Could not reproduce in the new world and couldn't restore current world :(
Some older save is loaded without issues. Between these saves I didn't much except may be started crafts/experiments with Iron Jetpacks.

**Comment by Jack-McKalling** [comment]
The issue described by this report was fixed in version 1.1.12, so this report's been closed. Should you still have any problems with crafting any of the jetpacks, or anything regarding colossal chests, you should create a new report. Good to hear it's now working as expected!

There is a slight chance your current world got corrupted in this process, if this is the case you should probably ask for help on the discord, as that's not something that can be fixed by the mod.
