### ISSUE TITLE
Tools which are used but not consumed in recipes are not supported

### ISSUE THREAD

**Issue by Adirelle** [CyclopsMC/IntegratedCrafting#36]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Some mod introduces items that are needed in recipes but are not consumed. Technically, the recipes consumes some of their durability. Examples: the Transmutation Stone of Retro-Exchange, the saws of Forge Multipart, the hammer and wire cutter of Immersive Engineering, copying variables in Integrated Dynamics...

If I wanted to craft 8 plates using the IE's hammer, the same hammer could be used and re-used each time, but the crafter complains about missing 7 hammers.

I'd like a way to tell the crafter that the hammer will not be consumed and that only one can be reused several times. I am not sure how this could be handled, maybe a flag in the Logic Programmer when creating the recipe ? (e.g. "this item will not be consumed").

**Comment by rubensworks** [comment]
Hmm, that might be tricky (when taking into account parallelization), but important to have indeed.

**Comment by Corfiot** [comment]
This is very needed for automation of dyes using pestle and mortar, too.

An additional complication to this is that you would need a way to specify which slots in a recipe should not be pulled from the machine/crafting table when the recipe is done, which could be a bitch, since most machines have to be set to auto-export and not all mods are smart enough to "keep" their reusable items.

This could be mitigated if scope is reduced a bit, i.e. only implement this for the crafting interface import setup, ignoring the paired importer setup. This should be enough for most recipes I've come across.

**Comment by Jack-McKalling** [comment]
Another reason to have this, is when automating the crafting of Mystical Agriculture essences using the (infinite uses) infusion crystal.

**Comment by rubensworks** [comment]
Will be added in the upcoming release of IC.
